-- LUMI DATABASE SCHEMA & AUTH MIGRATION

-- 1. CLEAR EXISTING DEVELOPMENT DATA
-- We must clear old unauthenticated data because it has no user_id to associate with.
-- (This prevents foreign key errors when enforcing the NOT NULL user_id constraint)
TRUNCATE TABLE public.classes, public.tasks, public.activities, public.push_subscriptions RESTART IDENTITY;

-- 2. CREATE CORE TABLES (If they don't exist yet)
create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  title text not null,
  day_of_week text not null,
  start_time text not null,
  end_time text not null,
  room text,
  faculty text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  due_date date,
  priority text not null check (priority in ('High', 'Medium', 'Low')),
  estimated_minutes integer,
  completed boolean default false not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null,
  date date not null,
  start_time text not null,
  end_time text not null,
  location text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.push_subscriptions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid,
  device_id text not null unique,
  endpoint text not null,
  subscription jsonb not null,
  timezone text default 'UTC' not null,
  briefing_time text default '07:00' not null,
  briefing_enabled boolean default true not null,
  last_briefing_date text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. ADD USER_ID & FOREIGN KEYS
do $$ 
begin
  if not exists (select 1 from information_schema.columns where table_name = 'classes' and column_name = 'user_id') then
    alter table public.classes add column user_id uuid references auth.users(id) default auth.uid() not null;
  end if;
  
  if not exists (select 1 from information_schema.columns where table_name = 'tasks' and column_name = 'user_id') then
    alter table public.tasks add column user_id uuid references auth.users(id) default auth.uid() not null;
  end if;

  if not exists (select 1 from information_schema.columns where table_name = 'activities' and column_name = 'user_id') then
    alter table public.activities add column user_id uuid references auth.users(id) default auth.uid() not null;
  end if;
end $$;

alter table public.push_subscriptions alter column user_id set default auth.uid();
alter table public.push_subscriptions alter column user_id set not null;

-- Safely add FK to push_subscriptions if missing
do $$ 
begin
  if not exists (
    select 1 
    from information_schema.table_constraints 
    where constraint_name = 'push_subscriptions_user_id_fkey'
  ) then
    alter table public.push_subscriptions add constraint push_subscriptions_user_id_fkey foreign key (user_id) references auth.users(id);
  end if;
end $$;

-- 4. ENABLE RLS
alter table public.classes enable row level security;
alter table public.tasks enable row level security;
alter table public.activities enable row level security;
alter table public.push_subscriptions enable row level security;

-- 5. DROP OLD ANONYMOUS POLICIES
drop policy if exists "Enable all access for classes" on public.classes;
drop policy if exists "Enable all access for tasks" on public.tasks;
drop policy if exists "Enable all access for activities" on public.activities;
drop policy if exists "Allow anon insert" on public.push_subscriptions;
drop policy if exists "Allow anon select" on public.push_subscriptions;
drop policy if exists "Allow anon update" on public.push_subscriptions;
drop policy if exists "Allow anon delete" on public.push_subscriptions;

-- 6. CREATE STRICT AUTHENTICATED POLICIES
-- Classes
drop policy if exists "Users can manage their own classes" on public.classes;
create policy "Users can manage their own classes" 
  on public.classes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Tasks
drop policy if exists "Users can manage their own tasks" on public.tasks;
create policy "Users can manage their own tasks" 
  on public.tasks for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Activities
drop policy if exists "Users can manage their own activities" on public.activities;
create policy "Users can manage their own activities" 
  on public.activities for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Push Subscriptions
drop policy if exists "Users can manage their own push subscriptions" on public.push_subscriptions;
create policy "Users can manage their own push subscriptions" 
  on public.push_subscriptions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 7. PROFILES TABLE
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles enable row level security;

drop policy if exists "Users can manage their own profile" on public.profiles;
create policy "Users can manage their own profile" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
